In [1]:
print("officially started with my data science journey...! so happy and excited :)  ")

officially started with my data science journey...! so happy and excited :)  


# Started with Numpy:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.empty(3)

array([0., 0., 0.])

In [8]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [12]:
np.linspace(5,10,num=10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [11]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [15]:
np.full_like(9,4)

array(4)

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
a = np.array([[1,2] ,[3,4]])
np.tile(a,[1,5])

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4]])

In [23]:
a.dtype

dtype('int32')

In [24]:
a.shape


(2, 2)

In [25]:
a.ndim

2

In [26]:
a.size

4

In [28]:
a = np.array("2")

In [29]:
a.ndim

0

In [30]:
a.dtype

dtype('<U1')

In [36]:
a1 = np.array([1,5])
a2 = np.array([8,9])
res = np.hstack((a1,a2))
print(res)

[1 5 8 9]


In [40]:
res = np.vstack((a1,a2))
print(res)

[[1 5]
 [8 9]]


In [41]:
np.random.rand(2,3)

array([[0.0159525 , 0.15826689, 0.52834662],
       [0.66264166, 0.00234544, 0.51936086]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [45]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [46]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.concatenate((a1,a2))

array([1, 5, 8, 9])

In [54]:
a1 = np.array([[1,5,3,4,5,8]])
a1.reshape(3,2)

array([[1, 5],
       [3, 4],
       [5, 8]])